DATASET_FINE: /home/emaraic/semanticSegmentation/datasets/cityscapes
DATASET_COARSE: /home/emaraic/semanticSegmentation/datasets/CityscapesExtra

USING_COARSE: False
BACKEND_NETWORK: MOBILENET

USING_GPU: TRUE
GPU_ID: 0

PRETRAINED_SHUFFLENET: /home/emaraic/semanticSegmentation/Repos/deeplabResnext/models/ShuffleNet_1g8_Top1_67.408_Top5_87.258.pth
PRETRAINED_MOBILENET: /home/emaraic/semanticSegmentation/Repos/deeplabResnext/models/mobilenet_v2.pth
PRETRAINED_DarkNET19: /home/emaraic/semanticSegmentation/Repos/deeplabResnext/models/darknet19_448.weights

